### ISSUE TITLE
Using GitHub container registry

### ISSUE THREAD

**Issue by naesheim** [eficode-academy/github-actions-katas#25]
Consider using the GitHub provided container registry. It shortens down the kata and reduce the risk of any issues creating an account.

If you think it's a valuable contribution I can implement it.

**Comment by sofusalbertsen** [comment]
Yes please.
My impression on getting things to work with GHCR.io is less than ideal I must say, but let me hear if you think it will ease up the pedagogical intake.

**Comment by samuel-enderwitz-eficode** [comment]
Implemented with #69. This issue can be closed now.
